services:
    app:
        image: php:8.4-apache
        container_name: hs-php-app
        build:
            context: docker
            args:
                USER_ID: "${USER_ID-33}"
                PHP_VERSION: 804
        volumes:
            - doc-root:/var/www/html
        ports:
            - "8090:80"
        networks:
            - default
        depends_on:
            db:
                condition: service_healthy
        environment:
            XDEBUG_MODE: debug,coverage
            XDEBUG_CONFIG: >-
                client_host=host.docker.internal
                discover_client_host=true
                log_level=0
        command:
            bash -c "chown -R www-data:www-data /var/www/html/public/uploads && apache2-foreground"

    messenger:
        image: php:8.4-apache
        container_name: hs-php-messenger
        build:
            context: docker
            args:
                USER_ID: "${USER_ID-33}"
                PHP_VERSION: 804
        volumes:
            - doc-root:/var/www/html
        networks:
            - default
        depends_on:
            db:
                condition: service_healthy
        environment:
            XDEBUG_MODE: debug,coverage
            XDEBUG_CONFIG: >-
                client_host=host.docker.internal
                discover_client_host=true
                log_level=0
        command: php bin/console messenger:consume async -vv
        user: www-data

    db:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        container_name: hs-php-db
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        ports:
            - "3399:5432"
        networks:
            - default
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - db-data:/var/lib/postgresql/data:rw

    maildev:
        image: "maildev/maildev:latest"
        ports:
            - "1099:1080"

volumes:
    doc-root:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./"
    db-data:
